import { ToolRegistryItem } from './types';

export const CATEGORIES = [
  { id: 'all' as const, name: '全部工具', description: '浏览所有的开发辅助工具' },
  { id: 'image' as const, name: '图形与视觉', description: 'SVG 智能转换、色彩转换、Favicon 及 CSS 渐变' },
  { id: 'dev' as const, name: '编码与格式化', description: 'JSON/YAML、SQL 美化、Base64、时间戳及 JSON→TS 生成' },
  { id: 'crypto' as const, name: '加解密', description: 'RSA/AES、哈希计算、JWT 调试及随机密码生成' },
  { id: 'text' as const, name: '文本与解析', description: '正则表达式测试、文本处理、Cron 解析及代码场' },
  { id: 'ops' as const, name: '运维与配置', description: 'Nginx 反向代理与静态配置、Docker Compose 模板生成及安全加固' },
];

export const ROLES = [];

export const TOOL_REGISTRY: ToolRegistryItem[] = [
  // ===== 图形与视觉 =====
  {
    id: 'svg-converter',
    title: 'SVG 智能转换',
    description: '支持粘贴SVG代码或上传文件，极速导出高保真 PNG, JPG, WEBP，并可自由调节尺寸、倍率及背景色。',
    category: 'image',
    keywords: ['svg', 'png', 'jpg', 'webp', 'converter', 'vector', '矢量图', '转换'],
    roles: ['developer', 'tester', 'designer'],
    privacy: 'local',
    icon: 'Image',
  },
  {
    id: 'color-box',
    title: '色彩转换与 Tailwind 调色板',
    description: '在 HEX、RGB、HSL 间双向极速转换色彩模式，自动生成全阶色调阴影，并包含全套标准 Tailwind 调色板参考。',
    category: 'image',
    keywords: ['color', 'hex', 'rgb', 'hsl', 'tailwind', 'palette', '色彩', '调色板', '转换'],
    roles: ['developer', 'designer'],
    privacy: 'local',
    icon: 'Palette',
  },
  {
    id: 'qrcode-gen',
    title: '二维码生成器',
    description: '支持自定义链接或文本内容，可自由调节纠错等级、白边、尺寸与斑点色彩，支持一键保存与剪贴板极速拷贝。',
    category: 'image',
    keywords: ['qrcode', 'qr', 'code', 'generate', 'link', 'wifi', '二维码', '生成器', '链接', '扫码'],
    roles: ['developer', 'tester', 'designer'],
    privacy: 'local',
    icon: 'QrCode',
  },
  {
    id: 'css-unit-converter',
    title: 'CSS 单位换算器',
    description: 'px / rem / em / vw / vh / pt / cm / mm / in 双向极速换算,可配置根字号、视口尺寸,点击即复制。',
    category: 'image',
    keywords: ['css', 'px', 'rem', 'em', 'vw', 'vh', 'unit', 'converter', '单位', '换算', '响应式'],
    roles: ['developer', 'designer'],
    privacy: 'local',
    icon: 'Ruler',
  },
  {
    id: 'css-gradient-generator',
    title: 'CSS 渐变生成器',
    description: '可视化生成 linear / radial / conic 三种渐变,支持多色断点、角度调节、8 种预设方案,一键复制 CSS 代码。',
    category: 'image',
    keywords: ['css', 'gradient', 'linear', 'radial', 'conic', '渐变', '背景', '可视化'],
    roles: ['developer', 'designer'],
    privacy: 'local',
    icon: 'Palette',
  },
  {
    id: 'favicon-generator',
    title: 'Favicon 图标生成器',
    description: '上传图片或输入字母,自动生成 16/32/48/64/180/192/512 多尺寸 PNG favicon,附带 HTML link 标签代码。',
    category: 'image',
    keywords: ['favicon', 'icon', 'generator', 'apple-touch', 'pwa', '图标', '生成', '网站图标'],
    roles: ['developer', 'designer'],
    privacy: 'local',
    icon: 'Image',
  },
  {
    id: 'image-placeholder',
    title: 'SVG 占位图智能生成',
    description: '针对前端 UI 原型提供多尺寸 SVG/HTML 占位符图片生成，可定制尺寸、比例标签、底色与前景字色，支持一键下载或拷贝 Data URL 标签。',
    category: 'image',
    keywords: ['placeholder', 'image', 'svg', 'canvas', 'tag', 'mock', '占位图', '图片', '前端调试'],
    roles: ['developer', 'designer'],
    privacy: 'local',
    icon: 'Image',
  },

  // ===== 编码与格式化 =====
  {
    id: 'json-yaml',
    title: 'JSON / YAML 格式化与转换',
    description: 'JSON与YAML互相转换，支持语法校验、自动格式化缩进、一键压缩，适合处理配置文件。',
    category: 'dev',
    keywords: ['json', 'yaml', 'formatter', 'validator', 'converter', '格式化', '校验', '转换'],
    roles: ['developer', 'tester', 'ops'],
    privacy: 'local',
    icon: 'FileCode',
  },
  {
    id: 'sql-formatter',
    title: 'SQL 美化与压缩',
    description: '支持 MySQL / PostgreSQL / SQLite / SQL Server / BigQuery 等多种方言,一键美化、压缩、关键字大小写转换,带语法高亮。',
    category: 'dev',
    keywords: ['sql', 'format', 'beautify', 'minify', 'mysql', 'postgres', 'sqlite', 'tsql', 'bigquery', '格式化', '美化', '压缩'],
    roles: ['developer', 'tester', 'ops'],
    privacy: 'local',
    icon: 'Database',
  },
  {
    id: 'json-to-ts',
    title: 'JSON → TypeScript 接口生成',
    description: '粘贴 JSON 自动生成 TypeScript interface,智能识别嵌套结构、数组和 null 可选字段,一键复制 TS 代码。',
    category: 'dev',
    keywords: ['json', 'typescript', 'interface', 'type', 'generator', 'ts', '代码生成', '类型推断'],
    roles: ['developer', 'tester'],
    privacy: 'local',
    icon: 'FileCode',
  },
  {
    id: 'curl-converter',
    title: 'cURL → 代码转换器',
    description: '粘贴 cURL 命令,自动转换为 fetch / axios / Python requests / Go 代码,识别 URL、方法、请求头、请求体。',
    category: 'dev',
    keywords: ['curl', 'fetch', 'axios', 'python', 'requests', 'go', 'http', 'request', '代码转换', '命令转换'],
    roles: ['developer', 'tester'],
    privacy: 'local',
    icon: 'Terminal',
  },
  {
    id: 'http-request-tester',
    title: 'HTTP 请求测试器 (轻量 Postman)',
    description: '支持 GET/POST/PUT/DELETE 等全方法,可配置请求头、JSON/Form/Text 请求体,展示响应头、Body、状态码、耗时。',
    category: 'dev',
    keywords: ['http', 'request', 'postman', 'api', 'tester', 'fetch', 'rest', '接口测试', '请求'],
    roles: ['developer', 'tester', 'ops'],
    privacy: 'local',
    icon: 'Send',
  },
  {
    id: 'base64',
    title: 'Base64 编解码 (文本 & 图片)',
    description: '支持文本的 Base64 编解码，以及图片与 Base64 的双向转换，并附带优雅的图片预览与一键复制代码。',
    category: 'dev',
    keywords: ['base64', 'encode', 'decode', 'image', 'text', '编码', '解码', '图片转base64'],
    roles: ['developer', 'designer'],
    privacy: 'local',
    icon: 'Code',
  },
  {
    id: 'timestamp',
    title: '时间戳转换助手',
    description: '提供 Unix 时间戳与北京时间的双向极速转换，支持毫秒/秒级，并能自动显示当前最新的时间戳流。',
    category: 'dev',
    keywords: ['timestamp', 'epoch', 'date', 'time', '时间戳', '北京时间', '转换'],
    roles: ['developer', 'tester', 'ops'],
    privacy: 'local',
    icon: 'Clock',
  },
  {
    id: 'uuid-gen',
    title: 'UUID / ULID 批量生成器',
    description: '批量生成 Version 4 UUID 或单调递增的 ULID，可自定义生成数量，带有极速批量复制面板。',
    category: 'dev',
    keywords: ['uuid', 'guid', 'ulid', 'generator', 'bulk', 'random', '唯一标识符', '批量生成'],
    roles: ['developer', 'tester'],
    privacy: 'local',
    icon: 'Fingerprint',
  },
  {
    id: 'url-codec',
    title: 'URL 编解码 & 参数提取',
    description: '将复杂 URL 解析提取出干净的 Query Key-Value 字典并转换成 JSON，支持双向编辑、重新串联，以及特殊多字节字符的快速安全转义。',
    category: 'dev',
    keywords: ['url', 'query', 'params', 'encode', 'decode', 'parameter', 'codec', '编解码', '参数解析', '链接拼接'],
    roles: ['developer', 'ops', 'tester'],
    privacy: 'local',
    icon: 'Link',
  },
  {
    id: 'json-diff',
    title: 'JSON 结构树 Deep Diff 比对',
    description: '将两份 JSON 对象进行深度比对与树形还原，清晰直观地展示新增、删除、修改的键名路径和具体数据，支持一键美化排版。',
    category: 'dev',
    keywords: ['json', 'diff', 'compare', 'difference', 'checker', '比对', '差异', '校验'],
    roles: ['developer', 'tester', 'ops'],
    privacy: 'local',
    icon: 'GitCompare',
  },
  {
    id: 'code-diff',
    title: 'Git-Style 代码与文件 Diff 对比',
    description: '支持粘贴任意文本或拖拽上传本地文件，提供 Side-by-Side 双栏及 Inline 单栏 Git 差异色彩高亮比对。',
    category: 'dev',
    keywords: ['diff', 'compare', 'git', 'patch', 'merge', 'code', 'file', '代码比对', '文件对比'],
    roles: ['developer', 'tester', 'designer'],
    privacy: 'local',
    icon: 'GitCompare',
  },

  // ===== 加解密 =====
  {
    id: 'hash-crypto',
    title: '哈希、URL 与 HTML 编码助手',
    description: '一站式处理哈希计算（MD5, SHA-1, SHA-256）与多种常用编码（URL 编解码, HTML 实体转义），极其安全。',
    category: 'crypto',
    keywords: ['hash', 'md5', 'sha', 'url', 'html', 'encode', 'decode', '哈希', '编解码', '加密'],
    roles: ['developer', 'ops', 'tester'],
    privacy: 'local',
    icon: 'Hash',
  },
  {
    id: 'rsa-generator',
    title: 'RSA 密钥生成与测试',
    description: '在浏览器内本地生成 1024/2048/4096 位高强度 RSA 密钥对，并提供 RSA-OAEP 算法模式的文本加解密沙盒。',
    category: 'crypto',
    keywords: ['rsa', 'key', 'pair', 'generate', 'encrypt', 'decrypt', 'pem', 'pkcs8', '加解密', '密钥对', '非对称加密'],
    roles: ['developer', 'ops', 'tester'],
    privacy: 'local',
    icon: 'Lock',
  },
  {
    id: 'aes-crypto',
    title: 'AES 对称加解密',
    description: '支持 AES-128/192/256 分组算法，支持 CBC, ECB, CTR 等多种工作模式及 PKCS7 填充，可自由配置 IV 向量及 Hex/Base64 编码展现。',
    category: 'crypto',
    keywords: ['aes', 'encrypt', 'decrypt', 'key', 'iv', 'cbc', 'ecb', 'symmetric', '对称加密', '加解密'],
    roles: ['developer', 'ops', 'tester'],
    privacy: 'local',
    icon: 'KeyRound',
  },
  {
    id: 'jwt-debugger',
    title: 'JWT 解码与验证调试',
    description: '纯客户端解析 JSON Web Token (JWT)，高亮还原 Header、Payload 及 Signature 内容，并对令牌过期时间进行高精度本地校准与预警。',
    category: 'crypto',
    keywords: ['jwt', 'token', 'decode', 'payload', 'header', 'signature', 'debugger', '解析', '令牌', '调试'],
    roles: ['developer', 'tester', 'ops'],
    privacy: 'local',
    icon: 'Eye',
  },
  {
    id: 'random-password',
    title: '高强度随机密码生成',
    description: '利用浏览器硬件密码级随机数（CSPRNG）批量产生高强度口令，支持大/小写、数字、符号、相似字符排除，自动评估复杂度信息。',
    category: 'crypto',
    keywords: ['password', 'random', 'generator', 'csprng', 'strength', 'bulk', '密码生成', '随机口令', '安全'],
    roles: ['developer', 'tester', 'ops'],
    privacy: 'local',
    icon: 'ShieldCheck',
  },

  // ===== 文本与解析 =====
  {
    id: 'regex',
    title: '正则表达式测试器',
    description: '快速测试正则表达式，匹配文本并实时高亮显示匹配内容，内置多种常用开发、运维、业务正则模版，支持生成 JS/Python/Go 代码。',
    category: 'text',
    keywords: ['regex', 'regexp', 'test', 'match', 'pattern', '正则表达式', '测试', '高亮'],
    roles: ['developer', 'tester'],
    privacy: 'local',
    icon: 'SearchCode',
  },
  {
    id: 'text-editor',
    title: '高级文本处理器 & Markdown',
    description: '文本大小写转换、行去重、行排序、过滤空行，并配有极简优雅的 Markdown 实时排版与 HTML 渲染预览(支持 Mermaid 图表)。',
    category: 'text',
    keywords: ['text', 'case', 'sort', 'unique', 'markdown', 'preview', 'mermaid', '文本处理', '排版', '预览'],
    roles: ['developer', 'tester'],
    privacy: 'local',
    icon: 'FileText',
  },
  {
    id: 'cron-parser',
    title: 'Cron 表达式解析器',
    description: '将复杂的 Linux Crontab 定时器表达式翻译还原为极易阅读的中文描述，并预测未来 5 次的精确后台触发执行时间戳。',
    category: 'text',
    keywords: ['cron', 'crontab', 'parser', 'schedule', 'time', 'scheduler', '解析', '定时任务', '触发时间'],
    roles: ['developer', 'ops'],
    privacy: 'local',
    icon: 'ServerCrash',
  },
  {
    id: 'user-agent',
    title: 'User-Agent 分析诊断',
    description: '一键读取分析您的浏览器 UA 标识，识别操作系统、浏览器内核版本、排版引擎及物理硬件类型，支持模拟各主流设备 UA 环境。',
    category: 'text',
    keywords: ['ua', 'useragent', 'browser', 'os', 'engine', 'device', 'crawler', '微信', '爬虫', '分析'],
    roles: ['developer', 'tester'],
    privacy: 'local',
    icon: 'Compass',
  },
  {
    id: 'code-playground',
    title: 'HTML/CSS/JS 代码场',
    description: '类似 CodePen 的本地代码场,左编辑右实时预览,支持 HTML/CSS/JS 三件套,自动保存到浏览器,带语法高亮。',
    category: 'text',
    keywords: ['codepen', 'playground', 'html', 'css', 'js', 'live', 'preview', '代码场', '实时预览', '前端调试'],
    roles: ['developer', 'designer', 'tester'],
    privacy: 'local',
    icon: 'Code2',
  },

  // ===== 运维与配置 =====
  {
    id: 'ops-configs',
    title: 'Nginx 与 Docker 运维片段',
    description: '快速生成常用的 Nginx 反向代理、静态服务、HTTPS 证书配置，以及常用服务的 Docker Compose 配置模板。',
    category: 'ops',
    keywords: ['nginx', 'docker', 'docker-compose', 'reverse proxy', 'config', 'devops', '运维', '配置'],
    roles: ['developer', 'ops'],
    privacy: 'local',
    icon: 'Server',
  },
  {
    id: 'subnet-calculator',
    title: 'IP 子网掩码与 CIDR 计算器',
    description: '针对 IPv4 CIDR 网段信息（如 /24）进行极速拆解，计算网络号、子网掩码、广播地址、首末可用主机 IP 及可用主机上限，提供二进制直观面板。',
    category: 'ops',
    keywords: ['ip', 'cidr', 'subnet', 'mask', 'network', 'broadcast', 'host', 'calculator', '子网掩码', '计算器', '网段'],
    roles: ['developer', 'ops'],
    privacy: 'local',
    icon: 'Server',
  },
  {
    id: 'linux-cmd-helper',
    title: 'Linux 常用命令与日志 Grep 构造器',
    description: '可视化组装 Linux 日志检索指令，支持特定日期、小时或分钟精准排查，附带端口占用、Nginx、Docker 常用运维命令速查。',
    category: 'ops',
    keywords: ['linux', 'grep', 'cmd', 'command', 'bash', 'nginx', 'port', 'docker', 'log', '运维', '命令速查'],
    roles: ['developer', 'ops', 'tester'],
    privacy: 'local',
    icon: 'Terminal',
  },
  {
    id: 'http-status-helper',
    title: 'HTTP 状态码极速查询',
    description: '收录常用及生僻 HTTP 响应状态码，提供谈判缓存、错误诊断及 Nginx/Node.js 等后端的部署限流与慢超时等优化方案。',
    category: 'ops',
    keywords: ['http', 'status', 'code', 'rfc', 'nginx', '502', '504', '404', '301', '状态码', '查询'],
    roles: ['developer', 'ops', 'tester'],
    privacy: 'local',
    icon: 'Globe',
  }
];
